# Generated by Django 4.2.7 on 2024-02-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="foto_perfil",
            field=models.ImageField(
                blank=True, null=True, upload_to="assets/profile_pics/"
            ),
        ),
    ]
